// Verb/adjective deconjugation, per PLAN.md Phase 1: "attempt to strip known
// conjugation endings (past, negative, te-form, potential, passive,
// causative, etc.) against the query and check if a plausible dictionary
// form exists via the driver." Returns base-entry matches separately from
// `search()`'s direct matches; the UI decides how to render the banner
// ("食べた is the past tense of 食べる ->"), this module only returns the
// machine-readable `relation`.
//
// Candidates are generated by string-suffix manipulation of the raw query
// (works whether it's kanji+kana or pure kana, since JMdict headwords are
// stored as literal text either way) and only accepted if a JMdict entry
// actually has that exact text as a headword/reading *and* carries the verb
// or adjective part-of-speech tag the rule implies — this is what keeps
// "strip る, see if anything matches" from turning into noise.
//
// The suffix rules only cover regular ichidan/godan/i-adjective patterns —
// they don't know する/来る are irregular, and don't handle longer auxiliary
// chains. When they find nothing, kuromoji (see tokenizer.js) tokenizes the
// query and offers its own basic_form guesses as a second pass, verified
// against JMdict the same way but with a looser verb/adjective POS check
// (kuromoji doesn't tell us which JMdict verb-class tag applies) and a
// generic 'conjugated' relation instead of a specific one.
import { romajiToHiragana } from './romaji.js';
import { fetchEntriesByIds } from './dictionary-entries.js';
import { getTokenizer } from './tokenizer.js';

// Godan (u-verb) consonant rows: dictionary-form ending kana -> its a-row
// (used for negative/passive/causative stems) and e-row (potential stem).
const GODAN_ROWS = {
  う: { a: 'わ', e: 'え', pos: 'v5u' },
  く: { a: 'か', e: 'け', pos: 'v5k' },
  ぐ: { a: 'が', e: 'げ', pos: 'v5g' },
  す: { a: 'さ', e: 'せ', pos: 'v5s' },
  つ: { a: 'た', e: 'て', pos: 'v5t' },
  ぬ: { a: 'な', e: 'ね', pos: 'v5n' },
  ぶ: { a: 'ば', e: 'べ', pos: 'v5b' },
  む: { a: 'ま', e: 'め', pos: 'v5m' },
  る: { a: 'ら', e: 'れ', pos: 'v5r' },
};

// Godan past/te-form sound changes (onbin): 2-kana suffix -> which
// dictionary-form endings it could have come from, with their pos tag.
const GODAN_SOUND_CHANGES = {
  った: ['う', 'つ', 'る'],
  いた: ['く'],
  いだ: ['ぐ'],
  した: ['す'],
  んだ: ['ぬ', 'ぶ', 'む'],
  って: ['う', 'つ', 'る'],
  いて: ['く'],
  いで: ['ぐ'],
  して: ['す'],
  んで: ['ぬ', 'ぶ', 'む'],
};

function candidatesFor(query) {
  const out = []; // { candidate, relation, pos: string[] }

  // Ichidan (v1): stem + る
  if (query.length > 1) {
    const stem = query.slice(0, -1);
    const stem2 = query.slice(0, -2);
    const stem3 = query.slice(0, -3);
    if (query.endsWith('た')) out.push({ candidate: `${stem}る`, relation: 'past', pos: ['v1'] });
    if (query.endsWith('て')) out.push({ candidate: `${stem}る`, relation: 'te-form', pos: ['v1'] });
    if (query.endsWith('ない')) out.push({ candidate: `${stem2}る`, relation: 'negative', pos: ['v1'] });
    if (query.endsWith('られる')) out.push({ candidate: `${stem3}る`, relation: 'potential/passive', pos: ['v1'] });
    if (query.endsWith('させる')) out.push({ candidate: `${stem3}る`, relation: 'causative', pos: ['v1'] });
  }

  // Godan (v5*) past/te-form via sound-change table.
  if (query.length > 2) {
    const suffix = query.slice(-2);
    const changes = GODAN_SOUND_CHANGES[suffix];
    if (changes) {
      const stem = query.slice(0, -2);
      const relation = suffix.endsWith('た') || suffix.endsWith('だ') ? 'past' : 'te-form';
      for (const ending of changes) out.push({ candidate: `${stem}${ending}`, relation, pos: [GODAN_ROWS[ending].pos] });
    }
  }

  // Godan negative/potential/passive/causative via a-row/e-row stems.
  for (const [ending, row] of Object.entries(GODAN_ROWS)) {
    if (query.endsWith(`${row.a}ない`)) {
      out.push({ candidate: `${query.slice(0, -3)}${ending}`, relation: 'negative', pos: [row.pos] });
    }
    if (query.endsWith(`${row.e}る`)) {
      out.push({ candidate: `${query.slice(0, -2)}${ending}`, relation: 'potential', pos: [row.pos] });
    }
    if (query.endsWith(`${row.a}れる`)) {
      out.push({ candidate: `${query.slice(0, -3)}${ending}`, relation: 'passive', pos: [row.pos] });
    }
    if (query.endsWith(`${row.a}せる`)) {
      out.push({ candidate: `${query.slice(0, -3)}${ending}`, relation: 'causative', pos: [row.pos] });
    }
  }

  // I-adjectives (adj-i).
  if (query.length > 2) {
    if (query.endsWith('かった')) out.push({ candidate: `${query.slice(0, -3)}い`, relation: 'past', pos: ['adj-i'] });
    if (query.endsWith('くない')) out.push({ candidate: `${query.slice(0, -3)}い`, relation: 'negative', pos: ['adj-i'] });
    if (query.endsWith('くて')) out.push({ candidate: `${query.slice(0, -2)}い`, relation: 'te-form', pos: ['adj-i'] });
  }

  return out;
}

async function findEntriesForCandidate(driver, candidate, posTags) {
  const posPlaceholders = posTags.map(() => '?').join(',');
  const rows = await driver.all(
    `SELECT DISTINCT e.id FROM entries e
     LEFT JOIN entry_kanji ek ON ek.entry_id = e.id
     LEFT JOIN entry_readings er ON er.entry_id = e.id
     WHERE (ek.text = ? OR er.text = ?)
       AND EXISTS (
         SELECT 1 FROM entry_senses s
         JOIN tag_lists tl ON tl.id = s.pos_id, json_each(tl.json) p
         WHERE s.entry_id = e.id AND p.value IN (${posPlaceholders})
       )`,
    [candidate, candidate, ...posTags],
  );
  return rows.map((r) => r.id);
}

// Same shape as findEntriesForCandidate, but accepts any verb/adjective POS
// tag rather than a specific list — used for kuromoji-derived candidates,
// where we know the token was tagged as a verb (動詞) or adjective (形容詞)
// but not which JMdict verb-class tag (v1/v5*/vk/vs-i/adj-i/...) applies.
async function findEntriesForCandidateLoose(driver, candidate) {
  const rows = await driver.all(
    `SELECT DISTINCT e.id FROM entries e
     LEFT JOIN entry_kanji ek ON ek.entry_id = e.id
     LEFT JOIN entry_readings er ON er.entry_id = e.id
     WHERE (ek.text = ? OR er.text = ?)
       AND EXISTS (
         SELECT 1 FROM entry_senses s
         JOIN tag_lists tl ON tl.id = s.pos_id, json_each(tl.json) p
         WHERE s.entry_id = e.id AND (p.value LIKE 'v%' OR p.value LIKE 'adj%')
       )`,
    [candidate, candidate],
  );
  return rows.map((r) => r.id);
}

// Tokenizes the query and returns each verb/adjective token's dictionary
// (basic) form as a candidate — kuromoji's IPADIC already knows irregulars
// (する, 来る) and the full auxiliary chain, so this needs no rule table.
async function kuromojiCandidates(query) {
  const tokenizer = await getTokenizer();
  const seen = new Set();
  const out = [];
  for (const token of tokenizer.tokenize(query)) {
    if (token.pos !== '動詞' && token.pos !== '形容詞') continue;
    if (seen.has(token.basic_form)) continue;
    seen.add(token.basic_form);
    out.push({ candidate: token.basic_form, relation: 'conjugated' });
  }
  return out;
}

/**
 * @param {import('./sqlite-driver.js').DBDriver} driver
 * @param {string} queryText
 * @returns {Promise<Array<object & { relation: string, surface: string }>>}
 */
export async function deconjugate(driver, queryText) {
  const trimmed = (queryText ?? '').trim();
  // Same romaji handling as search() - a query typed in romaji (e.g.
  // "kirawareru") needs converting to kana (きらわれる) before the suffix
  // rules below can recognize it; romajiToHiragana falls back to null for
  // anything that isn't fully romaji (kanji, already-kana, mixed text), so
  // this just keeps the raw trimmed text for those.
  const query = romajiToHiragana(trimmed) ?? trimmed;
  if (!query) return [];

  const matches = [];
  const seenEntryIds = new Set();
  function collect(relation, entryIds) {
    for (const id of entryIds) {
      if (seenEntryIds.has(id)) continue;
      seenEntryIds.add(id);
      matches.push({ id, relation });
    }
  }

  for (const { candidate, relation, pos } of candidatesFor(query)) {
    if (candidate === query || candidate.length === 0) continue;
    collect(relation, await findEntriesForCandidate(driver, candidate, pos));
  }

  // Only fall back to kuromoji once the deterministic rules found nothing —
  // they're cheap, precise about relation labels, and cover the common
  // regular-conjugation cases, so there's no reason to pay for tokenization
  // when they've already answered the query.
  if (matches.length === 0) {
    for (const { candidate, relation } of await kuromojiCandidates(query)) {
      if (candidate === query || candidate.length === 0) continue;
      collect(relation, await findEntriesForCandidateLoose(driver, candidate));
    }
  }
  if (matches.length === 0) return [];

  const entries = await fetchEntriesByIds(driver, matches.map((m) => m.id));
  const relationById = new Map(matches.map((m) => [m.id, m.relation]));
  return entries.map((entry) => ({ ...entry, relation: relationById.get(entry.id), surface: queryText }));
}
