// Ported from cobysy/jconj-js (MIT), itself a port of Stuart McGraw's Python
// jconj (yamagoya/jconj) - a standalone program demonstrating the JMdictDB
// conjugation tables. See NOTICE.md for the full attribution chain.
//
// Trimmed to what this app needs: no CSV parsing (jconj-tables.json ships
// pre-built, generated by jconj-js's own `gulp build-conjtables`) and no
// onum footnote text, just the conjugated forms themselves.
//
// jconj-tables.json's `conjo` rows are 9-element arrays:
//   [pos, conj, neg, fml, onum, stem, okuri, euphr, euphk]
// `stem` is how many trailing characters to drop from the input text before
// appending okuri (and, if the word's tail is kana, euphr; if kanji, euphk -
// covering cases like する's potential where the kanji form switches to an
// entirely different word, 出来る, while the kana form uses でき).

function construct(txt, stem, okuri, euphr, euphk) {
  if (txt.length < 2) {
    throw new Error('Conjugatable words must be at least 2 characters long');
  }
  const checkchar = txt[txt.length - 2];
  const iskana = checkchar >= 'あ' && checkchar <= 'ん';
  if ((iskana && euphr) || (!iskana && euphk)) stem += 1;
  if (iskana) {
    return txt.slice(0, txt.length - stem) + (euphr || '') + (okuri || '');
  }
  return txt.slice(0, txt.length - stem) + (euphk || '') + (okuri || '');
}

const NEGFML = [
  [false, false],
  [false, true],
  [true, false],
  [true, true],
];

/**
 * @param {string} ktxt - kanji text to conjugate, or '' to skip
 * @param {string} rtxt - kana reading to conjugate, or '' to skip
 * @param {number} pos - jconj-tables.json `kwpos` id (see conjugate.js's POS_ID)
 * @param {object} tables - the parsed jconj-tables.json ({ conj, conjo, kwpos, ... })
 * @returns {Record<string, string>} keyed by `${pos},${conj},${neg},${fml}`,
 *   e.g. "39,1,true,false" -> "話さない". Multiple onum variants (e.g. the
 *   causative's ~せる/~す alternates) are combined into one ' / '-joined string.
 */
export function jconjugate(ktxt, rtxt, pos, tables) {
  const conjIds = Object.keys(tables.conj).map(Number).sort((a, b) => a - b);
  const combined = {};

  for (const conj of conjIds) {
    for (const [neg, fml] of NEGFML) {
      const variants = [];
      for (let onum = 1; onum < 10; onum++) {
        const row = tables.conjo[`${pos},${conj},${neg},${fml},${onum}`];
        if (!row) break;
        const [, , , , , stem, okuri, euphr, euphk] = row;
        const kt = ktxt ? construct(ktxt, stem, okuri, euphr, euphk) : '';
        const rt = rtxt ? construct(rtxt, stem, okuri, euphr, euphk) : '';
        variants.push(kt && rt ? `${kt}【${rt}】` : (kt || rt));
      }
      if (variants.length > 0) {
        combined[`${pos},${conj},${neg},${fml}`] = variants.join(' / ');
      }
    }
  }
  return combined;
}
