// Verb/adjective deconjugation, per PLAN.md Phase 1: "attempt to strip known
// conjugation endings (past, negative, te-form, potential, passive,
// causative, etc.) against the query and check if a plausible dictionary
// form exists via the driver." Returns base-entry matches separately from
// `search()`'s direct matches; the UI decides how to render the banner
// ("食べた is the past tense of 食べる ->"), this module only returns the
// machine-readable `relation`.
//
// Candidates are generated by string-suffix manipulation of the raw query
// (works whether it's kanji+kana or pure kana, since JMdict headwords are
// stored as literal text either way) and only accepted if a JMdict entry
// actually has that exact text as a headword/reading *and* carries the verb
// or adjective part-of-speech tag the rule implies — this is what keeps
// "strip る, see if anything matches" from turning into noise.
import { toHiragana } from './kana.js';
import { fetchEntriesByIds } from './entries.js';

// Godan (u-verb) consonant rows: dictionary-form ending kana -> its a-row
// (used for negative/passive/causative stems) and e-row (potential stem).
const GODAN_ROWS = {
  う: { a: 'わ', e: 'え', pos: 'v5u' },
  く: { a: 'か', e: 'け', pos: 'v5k' },
  ぐ: { a: 'が', e: 'げ', pos: 'v5g' },
  す: { a: 'さ', e: 'せ', pos: 'v5s' },
  つ: { a: 'た', e: 'て', pos: 'v5t' },
  ぬ: { a: 'な', e: 'ね', pos: 'v5n' },
  ぶ: { a: 'ば', e: 'べ', pos: 'v5b' },
  む: { a: 'ま', e: 'め', pos: 'v5m' },
  る: { a: 'ら', e: 'れ', pos: 'v5r' },
};

// Godan past/te-form sound changes (onbin): 2-kana suffix -> which
// dictionary-form endings it could have come from, with their pos tag.
const GODAN_SOUND_CHANGES = {
  った: ['う', 'つ', 'る'],
  いた: ['く'],
  いだ: ['ぐ'],
  した: ['す'],
  んだ: ['ぬ', 'ぶ', 'む'],
  って: ['う', 'つ', 'る'],
  いて: ['く'],
  いで: ['ぐ'],
  して: ['す'],
  んで: ['ぬ', 'ぶ', 'む'],
};

function candidatesFor(query) {
  const out = []; // { candidate, relation, pos: string[] }

  // Ichidan (v1): stem + る
  if (query.length > 1) {
    const stem = query.slice(0, -1);
    const stem2 = query.slice(0, -2);
    const stem3 = query.slice(0, -3);
    if (query.endsWith('た')) out.push({ candidate: `${stem}る`, relation: 'past', pos: ['v1'] });
    if (query.endsWith('て')) out.push({ candidate: `${stem}る`, relation: 'te-form', pos: ['v1'] });
    if (query.endsWith('ない')) out.push({ candidate: `${stem2}る`, relation: 'negative', pos: ['v1'] });
    if (query.endsWith('られる')) out.push({ candidate: `${stem3}る`, relation: 'potential/passive', pos: ['v1'] });
    if (query.endsWith('させる')) out.push({ candidate: `${stem3}る`, relation: 'causative', pos: ['v1'] });
  }

  // Godan (v5*) past/te-form via sound-change table.
  if (query.length > 2) {
    const suffix = query.slice(-2);
    const changes = GODAN_SOUND_CHANGES[suffix];
    if (changes) {
      const stem = query.slice(0, -2);
      const relation = suffix.endsWith('た') || suffix.endsWith('だ') ? 'past' : 'te-form';
      for (const ending of changes) out.push({ candidate: `${stem}${ending}`, relation, pos: [GODAN_ROWS[ending].pos] });
    }
  }

  // Godan negative/potential/passive/causative via a-row/e-row stems.
  for (const [ending, row] of Object.entries(GODAN_ROWS)) {
    if (query.endsWith(`${row.a}ない`)) {
      out.push({ candidate: `${query.slice(0, -3)}${ending}`, relation: 'negative', pos: [row.pos] });
    }
    if (query.endsWith(`${row.e}る`)) {
      out.push({ candidate: `${query.slice(0, -2)}${ending}`, relation: 'potential', pos: [row.pos] });
    }
    if (query.endsWith(`${row.a}れる`)) {
      out.push({ candidate: `${query.slice(0, -3)}${ending}`, relation: 'passive', pos: [row.pos] });
    }
    if (query.endsWith(`${row.a}せる`)) {
      out.push({ candidate: `${query.slice(0, -3)}${ending}`, relation: 'causative', pos: [row.pos] });
    }
  }

  // I-adjectives (adj-i).
  if (query.length > 2) {
    if (query.endsWith('かった')) out.push({ candidate: `${query.slice(0, -3)}い`, relation: 'past', pos: ['adj-i'] });
    if (query.endsWith('くない')) out.push({ candidate: `${query.slice(0, -3)}い`, relation: 'negative', pos: ['adj-i'] });
    if (query.endsWith('くて')) out.push({ candidate: `${query.slice(0, -2)}い`, relation: 'te-form', pos: ['adj-i'] });
  }

  return out;
}

async function findEntriesForCandidate(driver, candidate, posTags) {
  const posPlaceholders = posTags.map(() => '?').join(',');
  const rows = await driver.all(
    `SELECT DISTINCT e.id FROM entries e
     LEFT JOIN entry_kanji ek ON ek.entry_id = e.id
     LEFT JOIN entry_readings er ON er.entry_id = e.id
     WHERE (ek.text = ? OR er.text = ?)
       AND EXISTS (
         SELECT 1 FROM entry_senses s, json_each(s.pos) p
         WHERE s.entry_id = e.id AND p.value IN (${posPlaceholders})
       )`,
    [candidate, candidate, ...posTags],
  );
  return rows.map((r) => r.id);
}

/**
 * @param {import('../driver.js').DBDriver} driver
 * @param {string} queryText
 * @returns {Promise<Array<object & { relation: string, surface: string }>>}
 */
export async function deconjugate(driver, queryText) {
  const query = toHiragana((queryText ?? '').trim());
  if (!query) return [];

  const matches = [];
  const seenEntryIds = new Set();
  for (const { candidate, relation, pos } of candidatesFor(query)) {
    if (candidate === query || candidate.length === 0) continue;
    const entryIds = await findEntriesForCandidate(driver, candidate, pos);
    for (const id of entryIds) {
      if (seenEntryIds.has(id)) continue;
      seenEntryIds.add(id);
      matches.push({ id, relation });
    }
  }
  if (matches.length === 0) return [];

  const entries = await fetchEntriesByIds(driver, matches.map((m) => m.id));
  const relationById = new Map(matches.map((m) => [m.id, m.relation]));
  return entries.map((entry) => ({ ...entry, relation: relationById.get(entry.id), surface: queryText }));
}
